import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello, world!</h1>
      </main>

      <footer>
        <p className="text-xs">
          Frontend challenge by{' '}
          <a
            href="https://www.frontendmentor.io/challenges/advice-generator-app-QdUG-13db"
            target="_blank"
            rel="noreferrer"
          >
            frontendmentor.io
          </a>
          , done by Dominik Rubröder
        </p>
      </footer>
    </div>
  );
};

export default Home;
